### ISSUE TITLE
[FormBuilderSearchableDropdown] Missing assertion

### ISSUE THREAD

**Issue by rohit-suthar** [flutter-form-builder-ecosystem/form_builder_extra_fields#53]
Currently, if we use `FormBuilderSearchableDropdown` on custom object type then we have to pass `compareFn` because of this line 
`assert(T == String || compareFn != null)` in `FormBuilderSearchableDropdown`.

But this `compareFn` is used only if we set `showSelectedItems` to true in `popupProps`. Currently we have to pass compareFn in all the cases.

**Comment by deandreamatias** [comment]
Hi
Can use the bug template and edited this issue with new format?
Thanks

<details>
  <summary>Template</summary>

## Environment

**Package version:**  

<details>
  <summary>Flutter doctor</summary>


```
```

</details>

<details>
  <summary>Code sample</summary>



```dart
```

</details>

## Description

**Expected behavior:**

**Current behavior:**

## Steps to reproduce

1. This
2. Than that
3. Then

## Images   

## Stacktrace/Logcat 

</details>
